global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'express-app'
    metrics_path: '/api/v1/metrics'
    static_configs:
      - targets: ['app:8000']
        labels:
          group: 'api'
